// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_NumberCombiation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_NumberCombiation));
        
        string IMigrationMetadata.Id
        {
            get { return "201709021935008_Add_NumberCombiation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
